export const firstParts = [
  // 350 single-word, no curse words:
  "quantum",
  "neon",
  "vapor",
  "cyber",
  "static",
  "pixel",
  "glitch",
  "fractured",
  "lunar",
  "solar",
  "stellar",
  "cosmic",
  "abstract",
  "surreal",
  "mystic",
  "velvet",
  "vibrant",
  "synth",
  "digital",
  "analog",
  "electric",
  "radiant",
  "iridescent",
  "prism",
  "hyper",
  "ultra",
  "neo",
  "neu",
  "acid",
  "transcendent",
  "ethereal",
  "celestial",
  "divine",
  "infinite",
  "boundless",
  "exotic",
  "otherworldly",
  "spectral",
  "phantasm",
  "shadow",
  "mirage",
  "dizzy",
  "kaleidoscopic",
  "psychedelic",
  "trippy",
  "mellow",
  "glitter",
  "sparkly",
  "opalescent",
  "chromatic",
  "rainbow",
  "magical",
  "enigmatic",
  "mesmeric",
  "luminous",
  "twinkling",
  "frozen",
  "fiery",
  "blazing",
  "scorching",
  "shimmering",
  "dazzling",
  "vibrating",
  "pulsing",
  "bionic",
  "cybernetic",
  "mechanical",
  "virtual",
  "data",
  "algorithmic",
  "binary",
  "coded",
  "encrypted",
  "techno",
  "robotic",
  "mechanized",
  "wired",
  "streamlined",
  "fluid",
  "liquid",
  "spectrum",
  "luminescent",
  "flashing",
  "blinking",
  "radiating",
  "echoing",
  "resonant",
  "sonic",
  "aural",
  "psycho",
  "mad",
  "bizarre",
  "quirky",
  "odd",
  "eccentric",
  "abstracted",
  "enigmatic",
  "mystical",
  "zen",
  "astro",
  "galactic",
  "orbital",
  "planetary",
  "meteor",
  "cometary",
  "eclipse",
  "nebular",
  "interstellar",
  "void",
  "blackhole",
  "singularity",
  "subatomic",
  "molecular",
  "atomic",
  "nano",
  "micro",
  "minuscule",
  "pint-sized",
  "diminutive",
  "tiny",
  "minute",
  "fleeting",
  "ephemeral",
  "momentary",
  "transient",
  "vanishing",
  "fading",
  "waning",
  "glowing",
  "polychrome",
  "vibrating",
  "sonorous",
  "cacophonous",
  "muffled",
  "hazy",
  "misty",
  "foggy",
  "smoky",
  "clouded",
  "veiled",
  "obscure",
  "hidden",
  "masked",
  "covert",
  "cryptic",
  "mysterious",
  "arcane",
  "esoteric",
  "occult",
  "forbidden",
  "secret",
  "undercover",
  "shrouded",
  "dim",
  "shadowy",
  "gloomy",
  "somber",
  "morose",
  "bleak",
  "forlorn",
  "solitary",
  "lonely",
  "abandoned",
  "forsaken",
  "forgotten",
  "lost",
  "drifting",
  "wandering",
  "nomadic",
  "roving",
  "gypsy",
  "boho",
  "weho",
  "free",
  "liberated",
  "unbound",
  "wild",
  "untamed",
  "feral",
  "raw",
  "rugged",
  "barbaric",
  "savage",
  "brutal",
  "fierce",
  "raging",
  "roaring",
  "toxic",
  "corrosive",
  "burning",
  "balding",
  "demonic",
  "fiendish",
  "diabolical",
  "satanic",
  "sinister",
  "creepy",
  "spooky",
  "ghastly",
  "bloodstained",
  "grim",
  "haunted",
  "cursed",
  "jinxed",
  "hexed",,
  "confusing",
  "quirky",
  "crazy",
  "insane",
  "unhinged",
  "deranged",
  "madcap",
  "nutty",
  "hilarious",
  "silly",
  "droll",
  "quirky",
  "bizarre",
  "surrealist",
  "hypnotic",
  "mesmerizing",
  "captivating",
  "spellbinding",
  "transcendent",
  "otherworldly",
  "spiritual",
  "mystical",
  "unreal",
  "fantastical",
  "fey",
  "elusive",
  "slippery",
  "slick",
  "glossy",
  "shiny",
  "polished",
  "refined",
  "smooth",
  "velvet",
  "suave",
  "cool",
  "chill",
  "iced",
  "crisp",
  "breezy",
  "windy",
  "gusty",
  "brisk",
  "snappy",
  "jazzy",
  "funky",
  "soulful",
  "groovy",
  "rhythmic",
  "syncopated",
  "vibey",
  "atmospheric",
  "ambient",
  "mellow",
  "relaxed",
  "laidback",
  "chilled",
  "lo-fi",
  "vinyl",
  "crunchy",
  "gritty",
  "raw",
  "edgy",
  "sharp",
  "brilliant",
  "radiant",
  "incandescent",
  "blinding",
  "dazzling",
  "screaming",
  "roaring",
  "thundering",
  "explosive",

  // 50 single-word entries with curse words:
  "fucking",
  "goddamn",
  "motherfucking",
  "shithead",
  "assclad",
  "bitchin",
  "damn",
  "fucked",
  "fuckingrad",
  "fucktastic",
  "shitfaced",
  "assbackwards",
  "dumbfuck",
  "crap-tastic",
  "fuckedup",
  "bullshit",
  "screwthis",
  "fuckwad",
  "goddamned",
  "fucker",
  "asshat",
  "shitshow",
  "fuckery",
  "dammit",
  "fudge",
  "sonofabitch",
  "fuckin",
  "screwface",
  "pricklyfuck",
  "fuckzilla",
  "shitstorm",
  "fuckup",
  "bitchslap",
  "asswipe",
  "fuckface",
  "fuckinshit",
  "dickwad",
  "piss-off",
  "motherfucker",
  "fuckadoodle",
  "fuckinghell",
  "assmunch",
  "cocksmack",
  "fuckstick",
  "dumbass",
  "shitlord",
  "assfuck",
  "fucknut",
  "fuckingbastard",
  "cocksplat",

  // 80 multi-word entries with no curse words:
  "glitch in time",
  "silent neon dream",
  "quantum static haze",
  "digital twilight",
  "cybernetic mirage",
  "fuzzy pixel storm",
  "virtual moonlight",
  "electric echo",
  "vaporwave vision",
  "acid rain rainbow",
  "cosmic dust dance",
  "prismatic daydream",
  "holographic pulse",
  "static spectrum",
  "luminous circuit",
  "psychedelic wind",
  "crystalline night",
  "liquid starlight",
  "binary whisper",
  "algorithmic soul",
  "abstract echo",
  "surreal spark",
  "vague utopia",
  "ethereal static",
  "mystic haze",
  "magnetic dawn",
  "auroral shimmer",
  "solar breeze",
  "lunar whisper",
  "nebular glow",
  "cyber pulse",
  "dystopian glitch",
  "utopian shimmer",
  "prismatic void",
  "holographic drift",
  "synthetic wave",
  "luminous fog",
  "psychedelic mirage",
  "vinyl vortex",
  "electric flux",
  "fuzzy meltdown",
  "dusty echoes",
  "smoky skyline",
  "crystalline spark",
  "liquid dream",
  "static reverie",
  "virtual shimmer",
  "cyber dawn",
  "digital rift",
  "bioluminescent glow",
  "translucent vision",
  "vivid aura",
  "vibrant haze",
  "sultry twilight",
  "tactile echo",
  "glacial stream",
  "fiery ember",
  "copper sunrise",
  "rusty gears",
  "metallic thunder",
  "iridescent rain",
  "titanic surge",
  "minuscule ripple",
  "stellar journey",
  "astral drift",
  "cosmic ballet",
  "intergalactic groove",
  "dwarf constellation",
  "hyper loop",
  "super nova burst",
  "ultra wave",
  "subatomic spin",
  "atomic burst",
  "nano flicker",
  "macro dreamscape",
  "binary ballet",
  "algorithmic swirl",
  "abstract matrix",
  "surreal spiral",
  "vague illusion",

  // 20 multi-word entries with curse words:
  "fucking glitch fest",
  "goddamn neon nightmare",
  "motherfucking pixel party",
  "shithead static surge",
  "assclown cosmic meltdown",
  "bitchin digital storm",
  "damn electric fever",
  "fucked up liquid dream",
  "fucktastic binary blaze",
  "shitfaced holographic haze",
  "assbackwards cyber vortex",
  "dumbfuck quantum burst",
  "crap-tastic techno rave",
  "fucked static spiral",
  "bullshit neon riot",
  "screwthis radiant glitch",
  "fuckwad astral meltdown",
  "goddamned digital drift",
  "fucker cosmic chaos",
  "asshat virtual void"
];

export const secondParts = [
  // 370 single-word, no curse words:
  "cyborg",
  "android",
  "samurai",
  "ninja",
  "viking",
  "sorcerer",
  "wizard",
  "necromancer",
  "shaman",
  "bard",
  "jester",
  "clown",
  "maverick",
  "rogue",
  "outlaw",
  "vampire",
  "werewolf",
  "zombie",
  "ghoul",
  "phantom",
  "specter",
  "fiend",
  "monster",
  "beast",
  "minotaur",
  "centaur",
  "cyclops",
  "kraken",
  "leviathan",
  "titan",
  "giant",
  "colossus",
  "avatar",
  "icon",
  "idol",
  "champion",
  "gladiator",
  "knight",
  "paladin",
  "mercenary",
  "assassin",
  "spy",
  "agent",
  "operative",
  "mystic",
  "oracle",
  "seer",
  "prophet",
  "savant",
  "techie",
  "hacker",
  "glitch",
  "byte",
  "robot",
  "automaton",
  "drone",
  "golem",
  "construct",
  "behemoth",
  "juggernaut",
  "dreadnought",
  "overseer",
  "tyrant",
  "dictator",
  "czar",
  "emperor",
  "kingpin",
  "mogul",
  "baron",
  "don",
  "mafia",
  "gangster",
  "punk",
  "anarchist",
  "rebel",
  "iconoclast",
  "freeloader",
  "drifter",
  "wanderer",
  "nomad",
  "vagrant",
  "bum",
  "tramp",
  "hobo",
  "scoundrel",
  "rascal",
  "scamp",
  "rapscallion",
  "knave",
  "curmudgeon",
  "misfit",
  "degenerate",
  "reprobate",
  "pariah",
  "outcast",
  "miscreant",
  "villain",
  "antagonist",
  "baddie",
  "troublemaker",
  "devil",
  "imp",
  "pixie",
  "sprite",
  "fairy",
  "nymph",
  "siren",
  "selkie",
  "harpy",
  "banshee",
  "wraith",
  "shade",
  "revenant",
  "lich",
  "ossuary",
  "cadaver",
  "corpse",
  "mummy",
  "cryptid",
  "sasquatch",
  "bigfoot",
  "yeti",
  "abomination",
  "frankenstein",
  "mutation",
  "hybrid",
  "chimera",
  "griffin",
  "phoenix",
  "sphinx",
  "pegasus",
  "unicorn",
  "dragonkin",
  "wyrm",
  "drake",
  "serpent",
  "viper",
  "cobra",
  "scorpion",
  "tarantula",
  "insectoid",
  "arachnid",
  "roach",
  "mantis",
  "locust",
  "grasshopper",
  "beetle",
  "cicada",
  "wasp",
  "hornet",
  "ant",
  "termite",
  "spider",
  "tick",
  "leech",
  "parasite",
  "fungus",
  "mildew",
  "lichen",
  "algae",
  "contagion",
  "plague",
  "virus",
  "bacteria",
  "infestation",
  "swarm",
  "hive",
  "queen",
  "soldier",
  "commander",
  "captain",
  "admiral",
  "general",
  "marshal",
  "warlord",
  "legionnaire",
  "conqueror",
  "invader",
  "raider",
  "marauder",
  "bandit",
  "brigand",
  "plunderer",
  "looter",
  "scavenger",
  "despoiler",
  "dissident",
  "radical",
  "extremist",
  "fanatic",
  "zealot",
  "missionary",
  "evangelist",
  "preacher",
  "apostle",
  "disciple",
  "cultist",
  "slasher",
  "stalker",
  "vandal",
  "renegade",
  "freebooter",
  "corsair",
  "buccaneer",
  "pirate",
  "desperado",
  "shadow",
  "python",
  "anaconda",
  "mamba",
  "rattler",
  "sidewinder",
  "scalpel",
  "claw",
  "fang",
  "talon",
  "mortal",
  "spirit",
  "apparition",
  "entity",
  "echo",
  "anomaly",
  "oddity",
  "curiosity",
  "monolith",
  "toxin",
  "venom",
  "acid",
  "plasma",
  "quantum",
  "nova",
  "comet",
  "meteor",
  "galaxy",
  "orbit",
  "satellite",
  "eclipse",
  "zenith",
  "nadir",
  "paradox",
  "riddle",
  "enigma",
  "cipher",
  "code",
  "matrix",
  "labyrinth",
  "puzzle",
  "mystery",
  "myth",
  "legend",
  "epic",
  "saga",
  "ballad",
  "lore",
  "chronicle",
  "odyssey",
  "quest",
  "saga",
  "ballad",
  "lore",
  "chronicle",
  "odyssey",
  "quest",
  "venture",
  "explorer",
  "trailblazer",
  "pioneer",
  "voyager",
  "sidestepper",
  "stepper",
  "dabbler",
  "innovator",
  "crafter",
  "artist",
  "painter",
  "sculptor",
  "designer",
  "maker",
  "builder",
  "creator",
  "forger",
  "smith",
  "alchemist",
  "chemist",
  "experimenter",
  "tinkerer",
  "gadgeteer",
  "engineer",
  "programmer",
  "coder",
  "architect",
  "strategist",
  "tactician",
  "mastermind",
  "conspirator",
  "plotter",
  "schemer",
  "provocateur",
  "agitator",
  "instigator",
  "disruptor",
  "revolutionary",
  "subversive",
  "nonconformist",
  "dissenter",
  "questioner",
  "challenger",
  "defier",
  "breaker",
  "smash",
  "crusher",
  "demolisher",
  "striker",
  "blitz",
  "storm",
  "tempest",
  "fury",
  "rage",
  "wrath",
  "vortex",
  "cyclone",
  "tornado",
  "earthquake",
  "aftershock",
  "wildfire",
  "inferno",
  "blaze",
  "flash",
  "spark",
  "ember",
  "scorch",
  "surge",

  // 80 single-word entries with curse words:
  "fuckface",
  "shithead",
  "dumbass",
  "asswipe",
  "bastard",
  "motherfucker",
  "fuckwad",
  "fucknugget",
  "craplord",
  "shitlord",
  "fuckster",
  "asshat",
  "dickhead",
  "pissface",
  "fuckbucket",
  "fucker",
  "assclown",
  "shitbrain",
  "fuckmunch",
  "bitchface",
  "damnation",
  "fucktard",
  "shitfucker",
  "dumbfuck",
  "assmunch",
  "fuckwit",
  "goddamn",
  "fuckinghell",
  "fuckaroo",
  "crapdick",
  "dickwad",
  "asshole",
  "pissflap",
  "shitspit",
  "fuckstick",
  "motherfucking",
  "cocksmack",
  "pissoff",
  "fuckdoodle",
  "bitchslap",
  "fucksplode",
  "shitstorm",
  "assbiscuit",
  "fuckbomb",
  "dumbshit",
  "fuckmeister",
  "assfucker",
  "fuckado",
  "cocksucker",
  "dickface",
  "shitmunch",
  "assdick",
  "bitchwad",
  "shitbag",
  "asscracker",
  "dickmunch",
  "fuckingmoron",
  "assclump",
  "shitpickle",
  "fuckersaurus",
  "mothertruck",
  "asslicker",
  "fucksucker",
  "shitknuckle",
  "assnugget",
  "shitwad",
  "fuckzilla",
  "shitfaced",

  // 30 multi-word entries with no curse words:
  "shadow hunter",
  "silent reaper",
  "dark avenger",
  "lunar assassin",
  "cyber outlaw",
  "neon warrior",
  "digital ghost",
  "virtual ninja",
  "mechanical rogue",
  "phantom striker",
  "cosmic trickster",
  "quantum rebel",
  "stellar marauder",
  "cyborg sentinel",
  "rogue operative",
  "arcane enforcer",
  "pixelated bandit",
  "digital renegade",
  "cybernetic rebel",
  "galactic outlaw",
  "synthetic assassin",
  "mechanized rebel",
  "urban specter",
  "midnight rogue",
  "vintage trickster",
  "electric phantom",
  "ironic enigma",
  "dystopian prophet",
  "cosmic outlaw",
  "shadowy vigilante",

  // 20 multi-word entries with curse words:
  "fuckin' rebel king",
  "goddamn shadow slayer",
  "motherfucking digital ghost",
  "shitstorm ninja",
  "dumbass outlaw",
  "assclown avenger",
  "fucking cyber thug",
  "damn digital bandit",
  "fuckwad reaper",
  "shithead operative",
  "bitchin' phantom",
  "fucktastic trickster",
  "asswipe assassin",
  "craphead enforcer",
  "fuckin' rogue",
  "goddamn renegade",
  "motherfucking outlaw",
  "shitfaced sentinel",
  "dumbfuck vigilante",
  "asshat specter"
];
